
#ifndef LSB_STEGANOGRAPHY_COMMON_H
#define LSB_STEGANOGRAPHY_COMMON_H

#define MAGIC_STRING "*"

#define MAX_SECRET_SIZE 1

#define MAX_IMAGE_BUF_SIZE (MAX_IMAGE_BUF_SIZE * 8)

#define MAX_FILE_SUFFIX 4

#endif //LSB_STEGANOGRAPHY_COMMON_H
