
#ifndef LSB_STEGANOGRAPHY_COMMON_H
#define LSB_STEGANOGRAPHY_COMMON_H

#define MAGIC_STRING "*"

#define MAX_SECRET_BUF_SIZE 1024

#define MAX_IMAGE_BUF_SIZE (MAX_SECRET_BUF_SIZE * 8)

#define MAX_FILE_SUFFIX 4

#define DECODE_FILE_EXTN_SIZE 32

#define DECODE_FILE_SIZE 32

#endif //LSB_STEGANOGRAPHY_COMMON_H
